INSERT INTO "public"."products" ("id", "name", "description", "price", "attributes", "created_at", "updated_at", "tsv")
VALUES (1, 'Clover cut-out knitted top',
        'Taking form in a body-skimming knit with bold cut-out and cherry red for the festive season woman.', 100.99,
        '["colors:red", "colors:pink", "colors:orange", "size:xl", "size:x", "size:s", "categories:woman-top", "brand:amadeus", "collection:winter"]',
        '0001-01-01 00:00:00+00', '0001-01-01 00:00:00+00',
        array_to_tsvector('{"colors:red", "colors:pink", "colors:orange", "size:xl", "size:x", "size:s", "categories:woman-top", "brand:amadeus", "collection:winter"}')),
       (2, 'Victoria ruffle v-neck top',
        'A lightweight organza top featured layered ruffles and frill detailing with a cut-out and an open back. This item is from the Holiday 2023 Collection woman.',
        80.35,
        '["colors:white", "size:xl", "size:x", "size:s", "categories:woman-top", "brand:dearjose", "collection:winter"]',
        '0001-01-01 00:00:00+00', '0001-01-01 00:00:00+00',
        array_to_tsvector('{"colors:white", "size:xl", "size:x", "size:s", "categories:woman-top", "brand:dearjose", "collection:winter"}')),
       (3, 'Cup cake smocked cropped top',
        'Featuring a cropped length, it boasts a lovely style with pleated detailing for an impressive look. This cropped top is named as a sweet cupcake woman.',
        99.75,
        '["colors:red", "colors:pink", "colors:navy", "size:s", "size:x", "size:m", "categories:woman-top", "brand:dearjose", "collection:spring"]',
        '0001-01-01 00:00:00+00', '0001-01-01 00:00:00+00',
        array_to_tsvector('{"colors:red", "colors:pink", "colors:navy", "size:s", "size:x", "size:m", "categories:woman-top", "brand:dearjose", "collection:spring"}')),
       (4, 'Bunny off-shoulder poplin top',
        'Comfort abounds in an off-shoulder crop top with sleeve accents and elegant laps. Clover Bunny Top from the Holiday 2023 Collection woman.',
        75.25,
        '["colors:red", "colors:pink", "colors:green", "size:s", "size:x", "size:m", "categories:woman-top", "brand:amadeus", "collection:spring"]',
        '0001-01-01 00:00:00+00', '0001-01-01 00:00:00+00',
        array_to_tsvector('{"colors:red", "colors:pink", "colors:green", "size:s", "size:x", "size:m", "categories:woman-top", "brand:amadeus", "collection:spring"}')),
       (5, 'Poker girl knitted top',
        'Imagined in knitwear, this delicate top boasts a crew neckline, short sleeves and attractive buttons at the shoulders. Pair back with a high-waisted mini skirt or jeans for a feminine cool weather look woman.',
        85.25,
        '["colors:red", "colors:pink", "size:s", "size:x", "size:m", "categories:woman-top", "brand:amadeus", "collection:summer"]',
        '0001-01-01 00:00:00+00', '0001-01-01 00:00:00+00',
        array_to_tsvector('{"colors:red", "colors:pink", "size:s", "size:x", "size:m", "categories:woman-top", "brand:amadeus", "collection:summer"}'));